# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: false
  
  config.vm.box = "mitchellh/boot2docker"

  # config.vm.box = "hashicorp/precise64"
  # config.vm.provision "docker"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false


  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.network "forwarded_port", guest: 4243, host: 4243 #docker
  config.vm.network "forwarded_port", guest: 8384, host: 8385 #syncthing


  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.define "docker_host" do |docker_host|
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker_host"
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
    vb.memory = "768"
    vb.check_guest_additions = false
    vb.functional_vboxsf     = false
  end
  

  # b2d doesn't support NFS
  config.nfs.functional = false

  # b2d doesn't persist filesystem between reboots
  if config.ssh.respond_to?(:insert_key)
    config.ssh.insert_key = false
  end 
end
